In [9]:
x=3
y=4
sum = x+y
print(sum)

7


In [11]:
print(sum + 5)

12


In [13]:
import numpy as np

In [19]:
arr = np.array([1,2,3,4,5])
arr2d =np.array([[1,2,3], [4,5,6])
arr

array([1, 2, 3, 4, 5])

In [29]:
arr2d
arr2d.ndim

2

In [23]:
# Creazione di un array
arr = np.array([1, 2, 3, 4, 5])

# Utilizzo di alcuni metodi
print("Forma dell'array:", arr.shape) # Output: (5,)
print("Dimensioni dell'array:", arr.ndim) # Output: 1
print("Tipo di dati:", arr.dtype) # Output: int64 (varia a seconda della piattaforma)
print("Numero di elementi:", arr.size) # Output: 5
print("Somma degli elementi:", arr.sum()) # Output: 15
print("Media degli elementi:", arr.mean()) # Output: 3.0
print("Valore massimo:", arr.max()) # Output: 5
print("Indice del valore massimo:", arr.argmax()) # Output: 4



Forma dell'array: (5,)
Dimensioni dell'array: 1
Tipo di dati: int64
Numero di elementi: 5
Somma degli elementi: 15
Media degli elementi: 3.0
Valore massimo: 5
Indice del valore massimo: 4


In [31]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr = np.arange(6)
reshape_arr = arr.reshape((2,3))
print(reshape_arr)

[[0 1 2]
 [3 4 5]]


In [115]:
arr = np.arange(10,70)
print(arr.dtype)
arr=np.array(arr, dtype=float)
print(arr.dtype)
print(arr.shape)
arr = arr.reshape((2,3,10))
print(arr)
arr.ndim


int64
float64
(60,)
[[[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]
  [60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]]]


3